# Set variables with the rule: [start, end, pts]

avg_n = 100       # type in  <class 'int'>
exp_type = "S1"       # type in  <class 'str'>

[q0]
  freq_range = [4,8,1000]       # type in  <class 'list'>


[q1]
  freq_range = [3,9,3000]       # type in  <class 'list'>


